import { useState } from 'react';
import {
  getQualityScore,
  getProfile,
  getIndexRecommendations,
  getMLReadiness,
} from '../api/client';

interface Props {
  datasetId: string;
  datasetName?: string;
}

export default function ReportDownload({ datasetId, datasetName }: Props) {
  const [generating, setGenerating] = useState(false);

  const downloadJSON = async () => {
    setGenerating(true);
    try {
      const [score, profiles, indexes, ml] = await Promise.all([
        getQualityScore(datasetId),
        getProfile(datasetId),
        getIndexRecommendations(datasetId),
        getMLReadiness(datasetId),
      ]);

      const report = {
        generated_at: new Date().toISOString(),
        tool: 'DataProfi v1.0.0',
        dataset: { id: datasetId, name: datasetName || datasetId },
        quality_score: score,
        column_profiles: profiles,
        index_recommendations: indexes,
        ml_readiness: ml,
      };

      const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `dataprofi-report-${datasetId}.json`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  };

  const downloadMarkdown = async () => {
    setGenerating(true);
    try {
      const [score, profiles, indexes, ml] = await Promise.all([
        getQualityScore(datasetId),
        getProfile(datasetId),
        getIndexRecommendations(datasetId),
        getMLReadiness(datasetId),
      ]);

      let md = `# DataProfi Report\n\n`;
      md += `**Generated:** ${new Date().toLocaleString()}\n`;
      md += `**Dataset:** ${datasetName || datasetId}\n`;
      md += `**Rows:** ${score.row_count.toLocaleString()} | **Columns:** ${score.column_count}\n\n`;

      md += `## Quality Score: ${score.overall_score.toFixed(1)} / 100\n\n`;
      md += `| Dimension | Score |\n|-----------|-------|\n`;
      for (const [dim, val] of Object.entries(score.dimension_scores)) {
        md += `| ${dim} | ${(val as number).toFixed(1)} |\n`;
      }

      md += `\n## Column Profiles\n\n`;
      md += `| Column | Type | Completeness | Unique | Issues |\n|--------|------|-------------|--------|--------|\n`;
      for (const p of profiles) {
        md += `| ${p.name} | ${p.dtype} | ${p.completeness}% | ${p.unique_count} | ${p.quality_issues.length} |\n`;
      }

      if (indexes.length > 0) {
        md += `\n## Index Recommendations\n\n`;
        for (const idx of indexes) {
          md += `### ${idx.column} - ${idx.index_type.toUpperCase()} (${idx.priority})\n\n`;
          md += `${idx.reason}\n\n`;
          md += `\`\`\`sql\n${idx.sql}\n\`\`\`\n\n`;
        }
      }

      md += `## ML Readiness: ${ml.score.toFixed(0)}%\n\n`;
      for (const check of ml.checks) {
        const icon = check.passed ? '[PASS]' : '[FAIL]';
        md += `- ${icon} **${check.name}**: ${check.message}\n`;
      }

      md += `\n---\n*Generated by DataProfi v1.0.0*\n`;

      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `dataprofi-report-${datasetId}.md`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      <button onClick={downloadMarkdown} disabled={generating} className="btn-primary text-xs">
        {generating ? 'Generating...' : 'Download Report'}
      </button>
      <button onClick={downloadJSON} disabled={generating} className="btn-secondary text-xs">
        Export JSON
      </button>
    </div>
  );
}
